sudo: required

services:
  - docker

language: java
jdk: oraclejdk8

env:
  DOCKER_COMPOSE_VERSION: 1.4.2

before_install:
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - /usr/local/bin/docker-compose build
  - /usr/local/bin/docker-compose run test
